"""
core/file_generate.py — Nexara Skills Warehouse
Generate files in any format: PDF, DOCX, HTML, TXT, MD, CSV, JSON, XML, XLSX.

Auto-installs required libraries on first use via pip.
Output always goes to ~/nexara_downloads/ and returns the full path
so Nexara can auto-send it to the user via Telegram.

Dependencies: auto-installed per format
  pdf  → fpdf2
  docx → python-docx
  xlsx → openpyxl
  others → stdlib only
Platforms: all
"""

import asyncio
import json
import logging
import os
import sys
import csv
import io
from datetime import datetime
from pathlib import Path

from skills.base import BaseSkill, SkillResult

logger = logging.getLogger("nexara.skill.file_generate")

DOWNLOADS_DIR = Path.home() / "nexara_downloads"


def _pip_install(package: str):
    """Install a package quietly via pip."""
    import subprocess
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", package, "-q", "--break-system-packages"],
        timeout=60,
    )


class FileGenerateSkill(BaseSkill):
    name        = "file_generate"
    description = (
        "Generate and save a file in any format: pdf, docx, html, txt, md, "
        "csv, json, xml, xlsx. Returns the file path so it can be sent to the user. "
        "Args: content (str), format (str), filename (str, no extension), "
        "title (str, optional)."
    )
    platforms   = ["all"]

    async def execute(
        self,
        content:  str  = "",
        format:   str  = "txt",
        filename: str  = "nexara_output",
        title:    str  = "",
        **kwargs,
    ) -> SkillResult:

        if not content:
            return SkillResult(success=False, output="", error="No content provided.")

        fmt = format.lower().strip().lstrip(".")
        DOWNLOADS_DIR.mkdir(parents=True, exist_ok=True)

        # Sanitise filename
        safe_name = "".join(c for c in filename if c.isalnum() or c in "-_. ").strip() or "nexara_output"
        out_path  = DOWNLOADS_DIR / f"{safe_name}.{fmt}"

        # Dispatch
        dispatch = {
            "txt":  self._txt,
            "md":   self._md,
            "html": self._html,
            "json": self._json,
            "xml":  self._xml,
            "csv":  self._csv,
            "pdf":  self._pdf,
            "docx": self._docx,
            "xlsx": self._xlsx,
        }

        if fmt not in dispatch:
            return SkillResult(
                success=False, output="",
                error=f"Unsupported format '{fmt}'. Supported: {', '.join(dispatch)}"
            )

        try:
            path = await asyncio.to_thread(dispatch[fmt], content, out_path, title)
            size = path.stat().st_size
            sz_str = f"{size / 1024:.1f} KB" if size < 1024 * 1024 else f"{size / 1024 / 1024:.1f} MB"
            return SkillResult(
                success=True,
                output=f"✅ File created: `{path}`  ({sz_str})",
                data={"path": str(path), "format": fmt, "size_bytes": size},
            )
        except Exception as exc:
            logger.exception("file_generate failed for format %s: %s", fmt, exc)
            return SkillResult(success=False, output="", error=str(exc))

    # ── Plain text ────────────────────────────────────────────────────────────

    def _txt(self, content: str, path: Path, title: str) -> Path:
        header = f"{title}\n{'=' * len(title)}\n\n" if title else ""
        path.write_text(header + content, encoding="utf-8")
        return path

    # ── Markdown ──────────────────────────────────────────────────────────────

    def _md(self, content: str, path: Path, title: str) -> Path:
        header = f"# {title}\n\n" if title else ""
        path.write_text(header + content, encoding="utf-8")
        return path

    # ── HTML ──────────────────────────────────────────────────────────────────

    def _html(self, content: str, path: Path, title: str) -> Path:
        import html as _html_mod
        safe_title   = _html_mod.escape(title or "Nexara Output")
        safe_content = _html_mod.escape(content).replace("\n", "<br>\n")
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{safe_title}</title>
  <style>
    body {{ font-family: Arial, sans-serif; max-width: 900px; margin: 40px auto;
           padding: 0 20px; line-height: 1.6; color: #333; }}
    h1   {{ border-bottom: 2px solid #333; padding-bottom: 8px; }}
    pre  {{ background: #f5f5f5; padding: 15px; border-radius: 4px;
           white-space: pre-wrap; word-wrap: break-word; }}
  </style>
</head>
<body>
  <h1>{safe_title}</h1>
  <pre>{safe_content}</pre>
  <footer style="margin-top:40px;color:#999;font-size:0.85em">
    Generated by Nexara · {datetime.now().strftime("%Y-%m-%d %H:%M")}
  </footer>
</body>
</html>"""
        path.write_text(html, encoding="utf-8")
        return path

    # ── JSON ──────────────────────────────────────────────────────────────────

    def _json(self, content: str, path: Path, title: str) -> Path:
        # Try to parse as JSON first; if not, wrap in object
        try:
            data = json.loads(content)
        except json.JSONDecodeError:
            data = {
                "title":     title or "Nexara Output",
                "content":   content,
                "generated": datetime.now().isoformat(),
            }
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
        return path

    # ── XML ───────────────────────────────────────────────────────────────────

    def _xml(self, content: str, path: Path, title: str) -> Path:
        import xml.etree.ElementTree as ET
        root    = ET.Element("document")
        if title:
            t_el  = ET.SubElement(root, "title")
            t_el.text = title
        body      = ET.SubElement(root, "body")
        body.text = content
        meta      = ET.SubElement(root, "meta")
        meta.set("generated", datetime.now().isoformat())
        meta.set("generator", "Nexara")
        tree = ET.ElementTree(root)
        ET.indent(tree, space="  ")
        tree.write(str(path), encoding="utf-8", xml_declaration=True)
        return path

    # ── CSV ───────────────────────────────────────────────────────────────────

    def _csv(self, content: str, path: Path, title: str) -> Path:
        # Try to parse existing CSV, otherwise wrap lines as single-column
        lines = content.strip().splitlines()
        with open(path, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            if title:
                writer.writerow([title])
                writer.writerow([])
            for line in lines:
                # If line contains commas it's likely already CSV-structured
                if "," in line:
                    writer.writerow(next(csv.reader([line])))
                else:
                    writer.writerow([line])
        return path

    # ── PDF ───────────────────────────────────────────────────────────────────

    def _pdf(self, content: str, path: Path, title: str) -> Path:
        try:
            from fpdf import FPDF
        except ImportError:
            _pip_install("fpdf2")
            from fpdf import FPDF

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pdf.set_margins(20, 20, 20)

        # Title
        if title:
            pdf.set_font("Helvetica", "B", 18)
            pdf.cell(0, 12, title, new_x="LMARGIN", new_y="NEXT", align="C")
            pdf.ln(4)
            pdf.set_draw_color(100, 100, 100)
            pdf.line(20, pdf.get_y(), 190, pdf.get_y())
            pdf.ln(6)

        # Body — handle unicode by replacing unsupported chars
        pdf.set_font("Helvetica", "", 11)
        safe_content = content.encode("latin-1", errors="replace").decode("latin-1")
        for line in safe_content.splitlines():
            if line.strip().startswith("#"):
                # Treat markdown headings as bold sections
                pdf.set_font("Helvetica", "B", 12)
                pdf.multi_cell(0, 7, line.lstrip("#").strip())
                pdf.set_font("Helvetica", "", 11)
            else:
                pdf.multi_cell(0, 6, line if line else " ")

        # Footer
        pdf.set_y(-15)
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(0, 10, f"Generated by Nexara · {datetime.now().strftime('%Y-%m-%d %H:%M')}", align="C")

        pdf.output(str(path))
        return path

    # ── DOCX ──────────────────────────────────────────────────────────────────

    def _docx(self, content: str, path: Path, title: str) -> Path:
        try:
            from docx import Document
            from docx.shared import Pt, RGBColor
        except ImportError:
            _pip_install("python-docx")
            from docx import Document
            from docx.shared import Pt, RGBColor

        doc = Document()

        if title:
            heading = doc.add_heading(title, level=0)
            heading.runs[0].font.color.rgb = RGBColor(0x1a, 0x1a, 0x1a)

        for line in content.splitlines():
            stripped = line.strip()
            if stripped.startswith("### "):
                doc.add_heading(stripped[4:], level=3)
            elif stripped.startswith("## "):
                doc.add_heading(stripped[3:], level=2)
            elif stripped.startswith("# "):
                doc.add_heading(stripped[2:], level=1)
            elif stripped.startswith("- ") or stripped.startswith("* "):
                doc.add_paragraph(stripped[2:], style="List Bullet")
            elif stripped == "":
                doc.add_paragraph("")
            else:
                doc.add_paragraph(stripped)

        # Footer
        section = doc.sections[0]
        footer  = section.footer.paragraphs[0]
        footer.text = f"Generated by Nexara · {datetime.now().strftime('%Y-%m-%d %H:%M')}"

        doc.save(str(path))
        return path

    # ── XLSX ──────────────────────────────────────────────────────────────────

    def _xlsx(self, content: str, path: Path, title: str) -> Path:
        try:
            import openpyxl
            from openpyxl.styles import Font, PatternFill, Alignment
        except ImportError:
            _pip_install("openpyxl")
            import openpyxl
            from openpyxl.styles import Font, PatternFill, Alignment

        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = title[:31] if title else "Sheet1"  # Excel 31-char sheet name limit

        row_num = 1
        if title:
            ws.cell(row=row_num, column=1, value=title).font = Font(bold=True, size=14)
            row_num += 2

        for line in content.strip().splitlines():
            if "," in line or "\t" in line:
                # Parse CSV-like line
                sep  = "\t" if "\t" in line else ","
                cols = [c.strip() for c in line.split(sep)]
                for col_num, val in enumerate(cols, 1):
                    ws.cell(row=row_num, column=col_num, value=val)
            else:
                ws.cell(row=row_num, column=1, value=line)
            row_num += 1

        # Auto-width columns
        for col in ws.columns:
            max_len = max((len(str(cell.value or "")) for cell in col), default=0)
            ws.column_dimensions[col[0].column_letter].width = min(max_len + 4, 80)

        wb.save(str(path))
        return path
